### ISSUE TITLE
Imgur broken after last update

### ISSUE THREAD

**Issue by riartem** [olav-st/screencloud-plugins#21] opened 2015-12-15 20:18 UTC
Imgur plugin not works with 1.2 version of app.

**Comment by olav-st** [comment] 2015-12-16 15:54
Probably a duplicate of https://github.com/olav-st/screencloud-plugins/issues/20

**Closed by olav-st** 2015-12-16 15:54 UTC

**Comment by riartem** [comment] 2015-12-16 19:14
Yes, fix for imgur plugin (1.5) work for that issue.
Thank you!
